name: cfp_flutter_ai_summary
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^10.1.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.8.5
  firebase_auth: ^4.7.3
  firebase_ui_auth: ^1.6.4
  json_annotation: ^4.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
